# Generated by Django 4.2.5 on 2025-10-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("voice", "0001_initial"),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="voice_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="voice.voicerecord",
            ),
        ),
    ]
