# Generated by Django 4.2.5 on 2025-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_best",
            field=models.BooleanField(default=False, verbose_name="是否为最佳答案"),
        ),
        migrations.AddField(
            model_name="question",
            name="asker_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="提问者ID"),
        ),
        migrations.AddField(
            model_name="question",
            name="asker_type",
            field=models.CharField(
                choices=[("elder", "老人端"), ("mom", "妈妈端")],
                default="elder",
                max_length=20,
                verbose_name="提问者类型",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="baby_age_months",
            field=models.IntegerField(blank=True, null=True, verbose_name="宝宝月龄"),
        ),
        migrations.AddField(
            model_name="question",
            name="urgency_level",
            field=models.CharField(
                choices=[("low", "不急"), ("normal", "一般"), ("high", "紧急")],
                default="normal",
                max_length=20,
                verbose_name="紧急程度",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
