# Generated by Django 4.2.5 on 2026-03-25 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_expertise_tags'),
        ('qa', '0003_answer_is_best_question_asker_id_question_asker_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_questions', to='user.user', verbose_name='提问的老人')),
            ],
            options={
                'verbose_name': '老人问题',
                'verbose_name_plural': '老人问题',
                'db_table': 'older_questions',
                'ordering': ['-create_time'],
            },
        ),
    ]
