# Generated by Django 4.2.5 on 2025-10-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("honors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_badges",
                to="user.user",
            ),
        ),
    ]
