# Generated by Django 4.2.5 on 2025-10-14 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_initial"),
        ("user", "0001_initial"),
        ("honors", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThankLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="感谢信标题")),
                ("content", models.TextField(verbose_name="感谢信内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parenting", "育儿指导"),
                            ("health", "健康咨询"),
                            ("education", "教育建议"),
                            ("psychology", "心理支持"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=100, verbose_name="发送者姓名"),
                ),
                (
                    "sender_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="发送者地区"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开显示"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recipient_expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_thank_letters",
                        to="user.user",
                        verbose_name="接收专家",
                    ),
                ),
                (
                    "related_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thank_letters",
                        to="qa.answer",
                        verbose_name="相关回答",
                    ),
                ),
            ],
            options={
                "verbose_name": "感谢信",
                "verbose_name_plural": "感谢信",
                "ordering": ["-create_time"],
            },
        ),
    ]
