# Generated by Django 4.2.5 on 2025-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honors", "0003_thankletter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thankletter",
            name="category",
        ),
        migrations.RemoveField(
            model_name="thankletter",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="thankletter",
            name="related_answer",
        ),
        migrations.RemoveField(
            model_name="thankletter",
            name="sender_location",
        ),
        migrations.RemoveField(
            model_name="thankletter",
            name="update_time",
        ),
        migrations.AddField(
            model_name="thankletter",
            name="help_category",
            field=models.CharField(
                default="其他",
                help_text="如：饮食健康、睡眠问题、性格培养等",
                max_length=50,
                verbose_name="帮助类别",
            ),
        ),
        migrations.AddField(
            model_name="thankletter",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="是否精选显示"),
        ),
        migrations.AddField(
            model_name="thankletter",
            name="sender_relation",
            field=models.CharField(
                default="家长",
                help_text="如：孩子的妈妈、爸爸、奶奶等",
                max_length=50,
                verbose_name="与受助者关系",
            ),
        ),
        migrations.AlterField(
            model_name="thankletter",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="thankletter",
            name="recipient_expert",
            field=models.CharField(
                help_text="被感谢的专家姓名", max_length=100, verbose_name="受感谢专家"
            ),
        ),
    ]
