# Generated by Django 4.2.5 on 2025-10-14 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voice_file_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "voice_format",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "transcribe_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("transcribed_text", models.TextField(blank=True, null=True)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_records",
                        to="qa.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_records",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
