# Generated by Django 4.2.5 on 2025-10-14 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="共享育儿专家", max_length=100)),
                ("role", models.CharField(default="育儿专家", max_length=50)),
                ("join_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("points", models.IntegerField(default=0)),
                ("answer_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("help_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sound",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off")],
                        default="on",
                        max_length=5,
                    ),
                ),
                (
                    "notification",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off")],
                        default="on",
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.CharField(max_length=100)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "related_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_records",
                        to="qa.answer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_records",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
