# Generated by Django 4.2.5 on 2025-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expertise_tags",
            field=models.JSONField(
                blank=True, default=list, help_text="老人擅长的领域标签"
            ),
        ),
    ]
