# Generated by Django 4.2.5 on 2026-03-25 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_olderquestion'),
        ('user', '0002_user_expertise_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlderFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_favorites', to='qa.answer', verbose_name='收藏的回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_favorites', to='user.user', verbose_name='收藏的老人')),
            ],
            options={
                'verbose_name': '老人收藏',
                'verbose_name_plural': '老人收藏',
                'db_table': 'older_favorites',
                'unique_together': {('user', 'answer')},
            },
        ),
    ]
