# Generated by Django 4.2.5 on 2026-03-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mominteractions', '0007_momanswer'),
        ('user', '0003_olderfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olderfavorite',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_favorites', to='mominteractions.momanswer', verbose_name='收藏的回答'),
        ),
    ]
