# Generated by Django 4.2.5 on 2025-10-18 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_user_expertise_tags"),
        ("qa", "0003_answer_is_best_question_asker_id_question_asker_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="妈妈用户名")),
                (
                    "join_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="妈妈加入APP的时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "妈妈用户",
                "verbose_name_plural": "妈妈用户",
                "db_table": "moms",
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="如：饮食健康、睡眠问题、行为培养等",
                        max_length=50,
                        verbose_name="标签分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="标签描述"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "问题标签",
                "verbose_name_plural": "问题标签",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="MomThankLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="感谢信标题")),
                ("content", models.TextField(verbose_name="感谢信内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发送时间"
                    ),
                ),
                (
                    "expert_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_thank_letters",
                        to="user.user",
                        verbose_name="感谢的专家",
                    ),
                ),
                (
                    "mom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_thank_letters",
                        to="mominteractions.momuser",
                        verbose_name="发送用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "妈妈感谢信",
                "verbose_name_plural": "妈妈感谢信",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MomQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="问题标题")),
                ("category", models.CharField(max_length=100, verbose_name="问题分类")),
                ("content", models.TextField(verbose_name="问题详细内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="问题发布时间"
                    ),
                ),
                (
                    "mom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mominteractions.momuser",
                        verbose_name="关联发布问题的妈妈用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "妈妈问题",
                "verbose_name_plural": "妈妈问题",
                "db_table": "mom_questions",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MomComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="妈妈的评论内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="评论发布时间"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mom_comments",
                        to="qa.answer",
                        verbose_name="关联妈妈评论的老人回答",
                    ),
                ),
                (
                    "mom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mominteractions.momuser",
                        verbose_name="关联发布评论的妈妈用户",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mominteractions.momquestion",
                        verbose_name="关联回答对应的妈妈问题（减少跨表查询）",
                    ),
                ),
            ],
            options={
                "verbose_name": "妈妈评论",
                "verbose_name_plural": "妈妈评论",
                "db_table": "comments",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="BabyCommonIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_title",
                    models.CharField(max_length=200, verbose_name="问题标题"),
                ),
                ("issue_description", models.TextField(verbose_name="问题描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feeding", "饮食健康"),
                            ("sleep", "睡眠问题"),
                            ("behavior", "行为培养"),
                            ("health", "日常护理"),
                            ("development", "知识启蒙"),
                            ("play", "趣味陪伴"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="问题分类",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="记录时间"
                    ),
                ),
                (
                    "mom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baby_issues",
                        to="mominteractions.momuser",
                        verbose_name="记录用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "宝宝常见问题",
                "verbose_name_plural": "宝宝常见问题",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MomLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="点赞时间"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mom_likes",
                        to="qa.answer",
                        verbose_name="关联妈妈点赞的老人回答",
                    ),
                ),
                (
                    "mom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="mominteractions.momuser",
                        verbose_name="关联点赞的妈妈用户",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="mominteractions.momquestion",
                        verbose_name="关联回答对应的妈妈问题（减少跨表查询）",
                    ),
                ),
            ],
            options={
                "verbose_name": "妈妈点赞",
                "verbose_name_plural": "妈妈点赞",
                "db_table": "mom_likes",
                "ordering": ["-create_time"],
                "unique_together": {("mom", "answer")},
            },
        ),
        migrations.CreateModel(
            name="AnswerFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="收藏时间"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="用户自定义的收藏分类标签",
                        verbose_name="收藏标签",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="收藏备注"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mom_favorites",
                        to="qa.answer",
                        verbose_name="被收藏回答",
                    ),
                ),
                (
                    "mom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="mominteractions.momuser",
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答收藏",
                "verbose_name_plural": "回答收藏",
                "unique_together": {("mom_user", "answer")},
            },
        ),
    ]
