# Generated by Django 4.2.5 on 2025-10-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mominteractions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="babycommonissue",
            name="issue_description",
        ),
        migrations.RemoveField(
            model_name="babycommonissue",
            name="issue_title",
        ),
        migrations.AlterModelTable(
            name="answerfavorite",
            table="mom_favorites",
        ),
        migrations.AlterModelTable(
            name="babycommonissue",
            table="mom_common_issues",
        ),
        migrations.AlterModelTable(
            name="momthankletter",
            table="mom_thank_letters",
        ),
        migrations.AlterModelTable(
            name="questiontag",
            table="mom_tags",
        ),
        migrations.DeleteModel(
            name="MomComment",
        ),
    ]
