# Generated by Django 4.2.5 on 2025-10-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mominteractions", "0002_remove_babycommonissue_issue_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerfavorite",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="answerfavorite",
            name="tags",
        ),
    ]
