# Generated by Django 4.2.5 on 2025-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mominteractions", "0003_remove_answerfavorite_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerfavorite",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="收藏备注"),
        ),
        migrations.AddField(
            model_name="answerfavorite",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="用户自定义的收藏分类标签",
                verbose_name="收藏标签",
            ),
        ),
    ]
