# Generated by Django 4.2.5 on 2025-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mominteractions", "0004_answerfavorite_notes_answerfavorite_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="babycommonissue",
            name="issue_description",
            field=models.TextField(default="暂无描述", verbose_name="问题描述"),
        ),
        migrations.AddField(
            model_name="babycommonissue",
            name="issue_title",
            field=models.CharField(
                default="未命名问题", max_length=200, verbose_name="问题标题"
            ),
        ),
    ]
