# Generated by Django 4.2.5 on 2025-10-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mominteractions", "0005_babycommonissue_issue_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="momlike",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="mominteractions.momquestion",
                verbose_name="关联回答对应的妈妈问题（减少跨表查询）",
            ),
        ),
    ]
