# Generated by Django 4.2.5 on 2026-03-25 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answer_is_best_question_asker_id_question_asker_type_and_more'),
        ('mominteractions', '0006_alter_momlike_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='回答内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答时间')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mom_answers', to='mominteractions.momuser', verbose_name='回答的妈妈')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mom_answers', to='qa.question', verbose_name='关联的问题')),
            ],
            options={
                'verbose_name': '妈妈回答',
                'verbose_name_plural': '妈妈回答',
                'db_table': 'mom_answer',
                'ordering': ['-create_time'],
            },
        ),
    ]
