# Generated by Django 4.2.5 on 2026-03-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_olderquestion'),
        ('mominteractions', '0007_momanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mom_answers', to='qa.olderquestion', verbose_name='关联的老人问题'),
        ),
    ]
